-- instructions: write a query to create a new table 
-- in your database based on the ERD provided above.

CREATE TABLE genres (
  genre_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  genre_name varchar(100),
  nationality varchar(255)
)